#!/bin/sh

set -e

case "$1" in
    configure)
    :
	# creating zato group if he isn't already there
	if ! getent group zato >/dev/null; then
	    addgroup zato
	fi
	# creating zato user if he isn't already there
	if ! getent passwd zato >/dev/null; then
	    adduser --ingroup zato --home /opt/zato --shell /bin/bash --gecos "Zato ESB" --disabled-password zato
	fi
	chown -R zato:zato /opt/zato
echo "export PATH
PATH="/opt/zato/1.1/bin:$PATH"">>/opt/zato/.profile
    ;;

    abort-upgrade | abort-remove | abort-deconfigure)
    :
    ;;

    *)
	echo "$0: Unrecognized option \`$1'" 1>&2
	exit 1
    ;;
esac

exit 0
