#! /bin/sh

set -e

case "$1" in  
    remove)
    :
	# Removing Zato User
	if grep -s -q "^zato:" /etc/passwd; then
	    echo "Removing user zato..."
	    userdel zato 2>&1 >/dev/null | grep -i  'error' || true
	else
	    echo "User zato already removed."
	fi
	rm -rf /opt/zato/current
    ;;
    purge)
    :
	#remove dirs with custom content
	rm -rf /opt/zato/ZATO_VERSION ||true
	rm -rf /etc/bash_completion.d/zato
	rm -rf /etc/init.d/zato
	rm -rf /etc/rc0.d/K99zato
	rm -rf /etc/rc1.d/K99zato
	rm -rf /etc/rc2.d/S99zato
	rm -rf /etc/rc3.d/S99zato
	rm -rf /etc/rc4.d/S99zato
	rm -rf /etc/rc5.d/S99zato
	rm -rf /etc/rc6.d/K99zato
	rm -rf /etc/systemd/system/multi-user.target.wants/zato.service
	rm -rf /etc/zato
	rm -rf /lib/systemd/system/zato.service
    ;;
    disappear | upgrade | failed-upgrade | abort-upgrade)
    :
	rm -rf /opt/zato/ZATO_VERSION
	rm -rf /opt/zato/current
    ;;
    *)
	echo "$0: Unrecognized option \`$1'" 1>&2
	exit 1
    ;;
esac


exit 0
