#!/bin/sh

set -e

case "$1" in
    configure)
    :
	# creating zato group if he isn't already there
	if ! getent group zato >/dev/null; then
	    addgroup zato
	fi
	# creating zato user if he isn't already there
	if ! getent passwd zato >/dev/null; then
	    adduser --ingroup zato --home /opt/zato --shell /bin/bash --gecos "Zato ESB" --disabled-password zato
	fi
	chown -R zato:zato /opt/zato
	if ! grep -q /opt/zato/current /opt/zato/.profile; then
echo "export PATH
PATH="/opt/zato/current/bin:$PATH"">>/opt/zato/.profile
        fi
        if [ -h "/opt/zato/current" ]; then
	    rm -Rf /opt/zato/current
	    ln -s /opt/zato/ZATO_VERSION /opt/zato/current
	else
	    ln -s /opt/zato/ZATO_VERSION /opt/zato/current
	fi
    if [ ! -d $HOME/nltk_data ]; then
        ln -s /opt/zato/ZATO_VERSION/nltk_data $HOME/nltk_data
    fi
    ;;

    abort-upgrade | abort-remove | abort-deconfigure)
    :
    ;;

    *)
	echo "$0: Unrecognized option \`$1'" 1>&2
	exit 1
    ;;
esac

exit 0
