#!/bin/sh

set -e
case "$1" in    
    install)
	# creating zato group if he isn't already there
	if ! getent group zato >/dev/null; then
	    addgroup zato
	fi
	# creating zato user if he isn't already there
	if ! getent passwd zato >/dev/null; then
	    adduser --ingroup zato --home /opt/zato --shell /bin/bash --gecos "Zato ESB" --disabled-password zato
	fi
	ZATO_BACKUP_DIR=/opt/zato/backup
	ZATO_DATE=`date +%Y%m%d_%H%M%S`
	ZATO_PATTERNS="/opt/zato/2.* /opt/zato/3.*"
	if [ ! -d "$ZATO_BACKUP_DIR" ]; then
	    mkdir $ZATO_BACKUP_DIR
	fi
	for directory in $ZATO_PATTERNS; do
	    mv -f $directory $ZATO_BACKUP_DIR/${directory##*/}_$ZATO_DATE
	done
        ;;
    upgrade|abort-upgrade)
	ZATO_BACKUP_DIR=/opt/zato/backup
	ZATO_DATE=`date +%Y%m%d_%H%M%S`
	ZATO_PATTERNS="/opt/zato/2.* /opt/zato/3.*"
	if [ ! -d "$ZATO_BACKUP_DIR" ]; then
	    mkdir $ZATO_BACKUP_DIR
	fi
	for directory in $ZATO_PATTERNS; do
	    mv -f $directory $ZATO_BACKUP_DIR/${directory##*/}_$ZATO_DATE
	done
        ;;
    *)
	echo "$0: Unrecognized option \`$1'" 1>&2
        exit 0
        ;;
esac

exit 0
