#!/bin/bash

cd /opt/zato

rm -f /opt/zato/env/qs-1/load-balancer/zato-lb-agent.pid
rm -f /opt/zato/env/qs-1/load-balancer/pidfile
/opt/zato/current/bin/zato start /opt/zato/env/qs-1/load-balancer --fg
