#!/bin/bash

ZATO_VERSION=`ls | sort -n | tail -1`

rm -f /opt/zato/env/qs-1/load-balancer/zato-lb-agent.pid
rm -f /opt/zato/env/qs-1/load-balancer/pidfile
/opt/zato/$ZATO_VERSION/bin/zato start /opt/zato/env/qs-1/load-balancer --fg
