VAGRANTFILE_API_VERSION = "2"
ENV["LC_ALL"] = "en_US.UTF-8"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "bento/centos-7.1"

  config.vm.provider "virtualbox" do |v|
    v.name = "oracle-box"
    v.memory = "1024"
  end
  config.vm.hostname = "oracle-box"
  config.vm.network "private_network", ip: "10.2.4.11"

  config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"
  config.vm.provision "shell",
    inline: "sudo yum -y update && sudo yum -y install zip unzip bc.x86_64 \
                    binutils.x86_64 gcc.x86_64 gcc-c++.x86_64 glibc.x86_64 \
                    glibc-devel.x86_64 libaio.x86_64 libaio-devel.x86_64 \
                    make.x86_64"
  config.vm.provision "shell", path: "./scripts/add_swap.sh"
  config.vm.provision "shell", path: "./scripts/install_oracle.sh"
  config.vm.provision "shell", path: "./scripts/configure_oracle.sh"

end
