---
- hosts: all
  become: yes

  pre_tasks:
    - name: Update apt cache if needed.
      apt: update_cache=yes cache_valid_time=3600

  tasks:
    - import_tasks: setup.yml

  handlers:
    - name: restart postgresql
      service: name=postgresql state=restarted
    - name: restart supervisor
      service: name=supervisor state=restarted

  vars:
    zato_bin: /opt/zato/current/bin/zato
    zato_web_admin_password: mysecretpassword
    dbname: zato
    dbuser: postgres
    dbpassword:

    postgresql_restarted_state: "restarted"
    postgresql_service_state: started
    postgresql_service_enabled: true

    postgresql_databases:
      - name: zato # required; the rest are optional
      # owner: zato
    postgresql_users:
      - name: zato #required; the rest are optional
        password: "{{ lookup('password', '/dev/null length=15 chars=ascii_letters') }}" # defaults to not set
        db: zato # defaults to not set
        priv: "ALL"

    postgresql_hba_entries:
      - { type: local, database: all, user: postgres, auth_method: trust }
      - { type: local, database: all, user: all, auth_method: trust }
      - { type: host, database: all, user: all, address: '127.0.0.1/32', auth_method: trust }
      - { type: host, database: all, user: all, address: '::1/128', auth_method: trust }
      - { type: host, database: all, user: all, address: '192.168.0.0/16', auth_method: trust }

  roles:
    - geerlingguy.postgresql
