#!/usr/bin/expect

set PACKAGE_RELEASE [lindex $argv 0]
set DISTRIBUTION [lindex $argv 1]
set CODENAME [lindex $argv 2]
set ARCHITECTURE [lindex $argv 3]
set PACKAGE_VERSION [lindex $argv 4]
set PATH /var/www/repo/$PACKAGE_RELEASE/2.0/$DISTRIBUTION/$CODENAME/$ARCHITECTURE
set PACKAGE zato-$PACKAGE_VERSION-$PACKAGE_RELEASE.$CODENAME.$ARCHITECTURE.rpm

spawn bash

exp_send "rpm --addsign $PATH/$PACKAGE\n"

expect {

    "Enter pass phrase:" {
        send "\r"
        exp_continue
    }
}
