VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

    config.vm.box = "bento/ubuntu-14.04"

    config.vm.provider "virtualbox" do |v|
        v.name = "sign-deb"
        #v.gui = true
        v.memory = "512"
    end
    config.vm.hostname = "sign-deb"

    config.vm.network "private_network", ip: "10.2.3.100"

    config.vm.provision "shell", 
        inline: "apt-get update && apt-get -y install vim ranger"
    config.vm.provision "shell", path: "files/aptly.sh"
    config.vm.provision "shell", path: "files/repo.sh", privileged: false

end
