VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

    config.vm.box = "bento/centos-6.7"

    config.vm.provider "virtualbox" do |v|
        v.name = "sign-rpm"
        #v.gui = true
        v.memory = "256"
    end
    config.vm.hostname = "sign-rpm"

    config.vm.network "private_network", ip: "10.2.3.101"

    config.vm.provision "shell", path: "files/repo.sh"

end
