CREATE DATABASE zato
    USER SYS IDENTIFIED BY password
    USER SYSTEM IDENTIFIED BY password
    USER zato IDENTIFIED BY zato
    LOGFILE GROUP 1 ('/u01/logs/zato/redo01a.log','/u02/logs/zato/redo01b.log') SIZE 100M BLOCKSIZE 512,
           GROUP 2 ('/u01/logs/zato/redo02a.log','/u02/logs/zato/redo02b.log') SIZE 100M BLOCKSIZE 512,
           GROUP 3 ('/u01/logs/zato/redo03a.log','/u02/logs/zato/redo03b.log') SIZE 100M BLOCKSIZE 512
    MAXLOGHISTORY 1
    MAXLOGFILES 16
    MAXLOGMEMBERS 3
    MAXDATAFILES 1024
    CHARACTER SET AL32UTF8
    NATIONAL CHARACTER SET AL32UTF8
    EXTENT MANAGEMENT LOCAL
    DATAFILE '/u02/zato/system01.dbf'
        SIZE 700M REUSE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED
    SYSAUX DATAFILE '/u02/zato/sysaux01.dbf'
        SIZE 550M REUSE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED
    DEFAULT TABLESPACE users
        DATAFILE '/u02/zato/users01.dbf'
        SIZE 500M REUSE AUTOEXTEND ON MAXSIZE UNLIMITED
    DEFAULT TEMPORARY TABLESPACE tempts1
        TEMPFILE '/u02/zato/temp01.dbf'
        SIZE 20M REUSE AUTOEXTEND ON NEXT 640K MAXSIZE UNLIMITED
    UNDO TABLESPACE undotbs1
        DATAFILE '/u02/zato/undotbs01.dbf'
        SIZE 200M REUSE AUTOEXTEND ON NEXT 5120K MAXSIZE UNLIMITED
        USER_DATA TABLESPACE usertbs
    DATAFILE '/u02/zato/usertbs01.dbf'
        SIZE 200M REUSE AUTOEXTEND ON MAXSIZE UNLIMITED;
EXIT;
