VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

    config.vm.box = "bento/ubuntu-14.04"

    config.vm.provider "virtualbox" do |v|
        v.name = "repo-box-ubuntu"
        #v.gui = true
        v.memory = "512"
    end
    config.vm.hostname = "repo-box-ubuntu"

    config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"

    config.vm.network "private_network", ip: "10.2.3.89"

    config.vm.provision "shell", path: "files/aptly.sh"
    config.vm.provision "shell", path: "files/apache.sh"
    config.vm.provision "shell", path: "files/repo.sh", privileged: false

end
